name: issue-annotation

on:
  issues:
    types: [opened, edited]

jobs:
  AnnotateIssue:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Install Research Software Encyclopedia
      run: |
        sudo apt-get update && sudo apt-get install -y python3 python3-pip python3-setuptools
        sudo pip3 install rse[all]
        rse --version
    - name: Parse Comment
      run: |
          echo "Title: ${{ github.event.issue.title }}"
          echo "Body: ${{ github.event.issue.body }}"
          echo "User: ${{ github.event.issue.user.login }}"
          echo "Sender: ${{ github.event.issue.sender.login }}"
          echo "Number: ${{ github.event.issue.number }}"
          echo "URL: ${{ github.event.issue.html_url }}"
          echo "Label: ${{ github.event.label }}"
