name: issue-annotation

on:
  issues:
    types: [opened, edited]

jobs:
  AnnotateIssue:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Install Research Software Encyclopedia
      run: |
        sudo apt-get update && sudo apt-get install -y python3 python3-pip python3-setuptools git
        git clone -b add/annotation-import https://github.com/rseng/rse
        cd rse
        sudo pip3 install -e .[all]
        #sudo pip3 install rse[all]
        rse --version
    - name: Parse Comment
      run: |
          echo "${{ github.event.issue.body }}" > new-issue.txt
          echo "Label: ${{ github.event.issue.labels[0].name }}"
          echo "Label: ${{ github.event.issue.label }}"
          # rse annotate (criteria|taxonomy) --file (filename) --username (user)
          echo "rse annotate ${{ github.event.issue.label }} --file new-issue.txt --username ${{ github.event.issue.user.login }}"
          rse annotate "${{ github.event.issue.label }}" --file new-issue.txt --username "${{ github.event.issue.user.login }}"
